# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# prebuilt docker images with toolchain
executors:
  setup-rv64gc:
    docker:
      - image: keystoneenclaveorg/keystone:init-rv64gc
  setup-rv32gc:
    docker:
      - image: keystoneenclaveorg/keystone:init-rv32gc



commands:
  update-riscv-toolchain-path:
    steps:
      - run: echo 'export PATH=/keystone/riscv/bin:/keystone/riscv64/bin:/keystone/riscv32/bin:$PATH' >> $BASH_ENV
  build-sdk:
    steps:
      - run: |
          cd /keystone/sdk
          rm -rf build
          mkdir build
          cd build
          KEYSTONE_SDK_DIR=$(pwd) cmake ..
          make install
  checkout-runtime:
    steps:
      - run: |
          git submodule sync
          git submodule update --init

  build-runtime:
    parameters:
      build-name:
        type: string
      build-dir:
        type: string
        default: build
      build-args:
        type: string
        default: ''

    steps:
      - run:
          name: << parameters.build-name >>
          environment:
            KEYSTONE_SDK_DIR: /keystone/sdk/build
          command: |
              mkdir -p << parameters.build-dir >>
              cd << parameters.build-dir >>
              cmake -DCMAKE_C_COMPILER=$(which riscv64-unknown-linux-gnu-gcc) \
                     -DCMAKE_OBJCOPY=$(which riscv64-unknown-linux-gnu-objcopy) \
                     << parameters.build-args >> ..
              make
          no-output-timeout: 120m

jobs:
  # The format job essentially runs clang-format against the Eyrie codebase. To
  # do so, we first query which clang-format git prefers. Then, we run git with
  # this clang-format. This ensures that the tool only checks files that have
  # been modified. Finally, we check the output of the tool and return an error
  # if some formatting changes are necessary.
  format:
    executor: setup-rv64gc
    steps:
      - checkout
      - checkout-runtime
      - update-riscv-toolchain-path
      - run: apt-get install clang-format -y
      - run:
          name: "test"
          environment:
            KEYSTONE_SDK_DIR: /keystone/sdk/build
          command: |
              FORMAT=$(git help -a | grep clang-format | tail -n1)
              FORMAT_RESULT=$(git $FORMAT)
              [ "$FORMAT_RESULT" = "no modified files to format" ] || [ "$FORMAT_RESULT" = "clang-format did not modify any files" ]
          no_output_timeout: 120m

  default-build:
    executor: setup-rv64gc
    steps:
      - checkout
      - checkout-runtime
      - update-riscv-toolchain-path
      - build-sdk
      - build-runtime:
          build-name: "Default build"
  use-freemem:
    executor: setup-rv64gc
    steps:
      - checkout
      - checkout-runtime
      - update-riscv-toolchain-path
      - build-sdk
      - build-runtime:
          build-name: "USE_FREEMEM"
          build-dir: build_freemem
          build-args: -DFREEMEM=on
  use_linux_syscall_use_freemem:
    executor: setup-rv64gc
    steps:
      - checkout
      - checkout-runtime
      - update-riscv-toolchain-path
      - build-sdk
      - build-runtime:
          build-name: "USE_LINUX_SYSCALL + USE_FREEMEM"
          build-dir: build_syscall_freemem
          build-args: -DLINUX_SYSCALL=on -DFREEMEM=on
  use_paging:
    executor: setup-rv64gc
    steps:
      - checkout
      - checkout-runtime
      - update-riscv-toolchain-path
      - build-sdk
      - build-runtime:
          build-name: "USE_PAGING"
          build-dir: build_paging
          build-args: -DFREEMEM=on -DPAGING=on
  use_package_crypto:
    executor: setup-rv64gc
    steps:
      - checkout
      - checkout-runtime
      - update-riscv-toolchain-path
      - build-sdk
      - build-runtime:
          build-name: "USE_PAGE_CRYPTO"
          build-dir: build_paging_crypto
          build-args: -DFREEMEM=on -DPAGING=on -DPAGE_CRYPTO=on
  use_page_hash:
    executor: setup-rv64gc
    steps:
      - checkout
      - checkout-runtime
      - update-riscv-toolchain-path
      - build-sdk
      - build-runtime:
          build-name: "USE_PAGE_HASH"
          build-dir: build_paging_hash
          build-args: -DFREEMEM=on -DPAGING=on -DPAGE_HASH=on
  use_page_crypto_use_page_hash:
    executor: setup-rv64gc
    steps:
      - checkout
      - checkout-runtime
      - update-riscv-toolchain-path
      - build-sdk
      - build-runtime:
          build-name: "USE_PAGE_CRYPTO + USE_PAGE_HASH"
          build-dir: build_paging_crypto_hash
          build-args: -DFREEMEM=on -DPAGING=on -DPAGE_CRYPTO=on -DPAGE_HASH=on

  test:
    executor: setup-rv64gc
    steps:
      - checkout
      - checkout-runtime
      - update-riscv-toolchain-path
      - build-sdk
      - run:
          name: "test"
          environment:
            KEYSTONE_SDK_DIR: /keystone/sdk/build
          command: |
              mkdir -p obj/test
              pushd obj/test
              cmake ../../test
              make
              ctest -VV || ( cat obj/test/Testing/Temporary/LastTest.log && false )
              popd
          no_output_timeout: 120m

workflows:
  build-and-test:
    jobs:
      - default-build
      - format
      - use-freemem:
          requires:
            - default-build
      - use_linux_syscall_use_freemem:
          requires:
            - default-build
      - use_package_crypto:
          requires:
            - default-build
      - use_paging:
          requires:
            - default-build
      - use_page_hash:
          requires:
            - default-build
      - use_page_crypto_use_page_hash:
          requires:
            - default-build
      - test:
          requires:
            - default-build
